In [1]:
from Matrix_graph import ws_opinion_graph, create_matrix_rep, GraphState
import numpy as np

In [2]:
TestGraf =  ws_opinion_graph(100,4,0.1,seed = 11)

In [3]:
MatrixGraf = create_matrix_rep(TestGraf)

In [4]:
MatrixGraf.matrix

array([[0.  , 0.42, 0.57, ..., 0.  , 0.47, 0.19],
       [0.29, 0.  , 0.46, ..., 0.  , 0.  , 0.25],
       [0.39, 0.57, 0.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.  , 0.73, 0.53],
       [0.59, 0.  , 0.  , ..., 0.37, 0.  , 0.89],
       [0.51, 0.39, 0.  , ..., 0.45, 0.28, 0.  ]], shape=(100, 100))

In [5]:
MatrixGraf.acceptrate


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
MatrixGraf.learningrate


array([0.15744858, 0.27725238, 0.41451392, 0.45787912, 0.40369126,
       0.11416328, 0.24376483, 0.16522273, 0.499521  , 0.15760614,
       0.19772578, 0.24288789, 0.12435468, 0.44815397, 0.35454457,
       0.1638993 , 0.29930742, 0.1314679 , 0.34439191, 0.19266529,
       0.11545557, 0.146095  , 0.32210505, 0.35479224, 0.22992026,
       0.35738097, 0.24082644, 0.1522636 , 0.22608411, 0.25810729,
       0.46505553, 0.14626415, 0.13446556, 0.32460081, 0.48535712,
       0.46290205, 0.38009762, 0.1267003 , 0.42256057, 0.37334989,
       0.1575721 , 0.28597749, 0.11972906, 0.42075039, 0.38745369,
       0.42185124, 0.40416626, 0.20690303, 0.41589621, 0.19966826,
       0.15515819, 0.25615601, 0.29913614, 0.21432886, 0.34231316,
       0.34100149, 0.19592706, 0.349027  , 0.24290117, 0.39387584,
       0.21616718, 0.41951737, 0.26604419, 0.32129609, 0.36933853,
       0.30735095, 0.20304727, 0.49175263, 0.13842216, 0.22996947,
       0.31964492, 0.11148019, 0.16196523, 0.41970577, 0.41352

In [7]:
MatrixGraf.opinions


array([-0.53, -0.  ,  0.12, -0.82, -0.49,  0.67, -0.67, -0.53,  0.73,
        0.15, -0.16,  0.01,  0.2 , -0.28, -0.51,  0.38,  0.21,  0.01,
        0.42,  0.06,  0.87, -0.39,  0.06, -0.02, -0.18,  0.11, -0.34,
        0.4 ,  0.52, -0.53, -0.04, -0.28, -0.63,  0.58, -0.08, -0.49,
        0.21, -0.39,  0.6 , -0.37, -0.8 , -0.4 , -0.19, -0.04,  0.61,
        0.25, -0.2 , -0.88, -0.47,  0.97, -0.05,  0.24, -0.72, -0.8 ,
        0.48,  0.11, -0.24, -0.23, -0.62, -0.44, -0.84,  0.46, -0.04,
       -0.53,  0.3 , -0.4 , -0.7 ,  0.12,  0.58, -0.83,  0.41, -0.41,
       -0.61, -0.88, -0.26,  0.29, -0.01,  0.49, -0.37, -0.23, -0.31,
        0.86,  0.71, -0.2 , -0.08, -0.23,  0.31, -0.77, -0.68, -0.12,
       -0.33,  0.48,  0.31,  0.05,  0.2 ,  0.24,  0.37,  0.66, -0.49,
        0.15])

In [8]:
MatrixGraf.type


array(['Human', 'Human', 'Human', 'Human', 'Human', 'Human', 'Human',
       'Human', 'Human', 'Human', 'Human', 'Human', 'Human', 'Human',
       'Human', 'Human', 'Human', 'Human', 'Human', 'Human', 'Human',
       'Human', 'Human', 'Human', 'Human', 'Human', 'Human', 'Human',
       'Human', 'Human', 'Human', 'Human', 'Human', 'Human', 'Human',
       'Human', 'Human', 'Human', 'Human', 'Human', 'Human', 'Human',
       'Human', 'Human', 'Human', 'Human', 'Human', 'Human', 'Human',
       'Human', 'Human', 'Human', 'Human', 'Human', 'Human', 'Human',
       'Human', 'Human', 'Human', 'Human', 'Human', 'Human', 'Human',
       'Human', 'Human', 'Human', 'Human', 'Human', 'Human', 'Human',
       'Human', 'Human', 'Human', 'Human', 'Human', 'Human', 'Human',
       'Human', 'Human', 'Human', 'Human', 'Human', 'Human', 'Human',
       'Human', 'Human', 'Human', 'Human', 'Human', 'Human', 'Human',
       'Human', 'Human', 'Human', 'Human', 'Human', 'Human', 'Human',
       'Human', 'Hum

In [9]:
weight_sum = MatrixGraf.matrix.sum(axis=0)
print(weight_sum)

[1.78 1.89 3.71 2.88 2.66 1.99 2.61 2.26 1.86 2.14 2.31 3.52 2.91 1.16
 2.1  1.15 1.36 2.08 1.78 2.24 2.15 2.47 2.44 1.84 2.07 2.4  2.37 3.73
 2.07 2.6  2.47 2.45 2.92 1.68 2.5  1.03 3.28 2.83 3.12 2.11 2.46 1.63
 2.22 2.53 2.75 1.28 1.94 2.44 2.61 1.1  1.77 2.13 2.72 1.74 1.06 2.99
 2.21 3.   2.07 3.17 2.07 2.57 3.08 2.5  3.2  2.17 1.17 1.71 2.15 2.09
 2.11 1.49 2.15 2.57 1.26 1.51 1.77 1.21 3.   1.86 2.22 3.21 1.25 1.54
 3.17 1.21 2.56 2.47 1.35 2.12 3.58 2.39 2.11 2.08 1.82 2.   2.33 1.97
 2.52 1.86]


In [10]:
weighted_neighbour_sum = MatrixGraf.matrix @ MatrixGraf.opinions
print(weighted_neighbour_sum)

[-0.1334 -0.6678 -0.9716  0.4806 -0.245  -1.145   0.1162 -0.1532 -0.7961
 -0.2206  0.2438 -0.3168 -0.2777  0.1373  0.1216 -0.1673  0.1153  0.1564
  0.8787  0.3619  0.0177  0.3258  0.0283 -0.5401 -0.2459  0.0834  0.6038
 -0.1361 -0.0123  0.1896 -0.3902 -0.3469  0.0568 -0.6239 -0.6795  0.0519
  0.2957 -0.0067 -1.2853 -0.8229  0.0619 -0.7483 -0.4948 -0.2167 -0.6773
 -0.1816  0.3356  0.2985 -0.4552 -0.6037 -0.4022 -0.1787 -0.1583  0.1533
 -0.6127 -1.0223 -0.4867 -0.6262 -0.8119 -1.3898 -0.4172 -0.3102 -0.6125
  0.0918 -0.9726 -0.1671  0.1268 -0.4811 -0.2381  0.6099  0.129  -1.014
 -0.9063 -0.5852 -0.5349 -1.1692 -0.3203 -0.1834 -0.223   0.4334  0.6438
 -0.0673  0.1454  0.7087  0.776  -0.3569 -0.8523 -0.224  -0.492  -0.6909
  0.1266 -0.0924  0.0321  0.7302  0.8306  0.5734  0.3146  0.1386  0.3404
 -0.1105]


In [11]:
avg_neighbour_opinion = np.divide(weighted_neighbour_sum, weight_sum,
                                   out=np.zeros_like(weighted_neighbour_sum), where=weight_sum != 0)
print(avg_neighbour_opinion)

[-0.07494382 -0.35333333 -0.26188679  0.166875   -0.09210526 -0.57537688
  0.04452107 -0.06778761 -0.42801075 -0.10308411  0.10554113 -0.09
 -0.09542955  0.11836207  0.05790476 -0.14547826  0.08477941  0.07519231
  0.49365169  0.1615625   0.00823256  0.13190283  0.01159836 -0.29353261
 -0.11879227  0.03475     0.25476793 -0.03648794 -0.00594203  0.07292308
 -0.15797571 -0.14159184  0.01945205 -0.37136905 -0.2718      0.05038835
  0.09015244 -0.00236749 -0.41195513 -0.39        0.0251626  -0.45907975
 -0.22288288 -0.08565217 -0.24629091 -0.141875    0.17298969  0.12233607
 -0.17440613 -0.54881818 -0.22723164 -0.08389671 -0.05819853  0.08810345
 -0.57801887 -0.34190635 -0.22022624 -0.20873333 -0.39222222 -0.43842271
 -0.20154589 -0.12070039 -0.19886364  0.03672    -0.3039375  -0.07700461
  0.10837607 -0.28134503 -0.11074419  0.29181818  0.06113744 -0.68053691
 -0.42153488 -0.22770428 -0.42452381 -0.77430464 -0.18096045 -0.15157025
 -0.07433333  0.23301075  0.29       -0.02096573  0.11632

In [12]:
weighted_neighbour_sum/weight_sum

array([-0.07494382, -0.35333333, -0.26188679,  0.166875  , -0.09210526,
       -0.57537688,  0.04452107, -0.06778761, -0.42801075, -0.10308411,
        0.10554113, -0.09      , -0.09542955,  0.11836207,  0.05790476,
       -0.14547826,  0.08477941,  0.07519231,  0.49365169,  0.1615625 ,
        0.00823256,  0.13190283,  0.01159836, -0.29353261, -0.11879227,
        0.03475   ,  0.25476793, -0.03648794, -0.00594203,  0.07292308,
       -0.15797571, -0.14159184,  0.01945205, -0.37136905, -0.2718    ,
        0.05038835,  0.09015244, -0.00236749, -0.41195513, -0.39      ,
        0.0251626 , -0.45907975, -0.22288288, -0.08565217, -0.24629091,
       -0.141875  ,  0.17298969,  0.12233607, -0.17440613, -0.54881818,
       -0.22723164, -0.08389671, -0.05819853,  0.08810345, -0.57801887,
       -0.34190635, -0.22022624, -0.20873333, -0.39222222, -0.43842271,
       -0.20154589, -0.12070039, -0.19886364,  0.03672   , -0.3039375 ,
       -0.07700461,  0.10837607, -0.28134503, -0.11074419,  0.29

In [13]:
MatrixGraf

GraphState(matrix=array([[0.  , 0.42, 0.57, ..., 0.  , 0.47, 0.19],
       [0.29, 0.  , 0.46, ..., 0.  , 0.  , 0.25],
       [0.39, 0.57, 0.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.  , 0.73, 0.53],
       [0.59, 0.  , 0.  , ..., 0.37, 0.  , 0.89],
       [0.51, 0.39, 0.  , ..., 0.45, 0.28, 0.  ]], shape=(100, 100)), opinions=array([-0.53, -0.  ,  0.12, -0.82, -0.49,  0.67, -0.67, -0.53,  0.73,
        0.15, -0.16,  0.01,  0.2 , -0.28, -0.51,  0.38,  0.21,  0.01,
        0.42,  0.06,  0.87, -0.39,  0.06, -0.02, -0.18,  0.11, -0.34,
        0.4 ,  0.52, -0.53, -0.04, -0.28, -0.63,  0.58, -0.08, -0.49,
        0.21, -0.39,  0.6 , -0.37, -0.8 , -0.4 , -0.19, -0.04,  0.61,
        0.25, -0.2 , -0.88, -0.47,  0.97, -0.05,  0.24, -0.72, -0.8 ,
        0.48,  0.11, -0.24, -0.23, -0.62, -0.44, -0.84,  0.46, -0.04,
       -0.53,  0.3 , -0.4 , -0.7 ,  0.12,  0.58, -0.83,  0.41, -0.41,
       -0.61, -0.88, -0.26,  0.29, -0.01,  0.49, -0.37, -0.23, -0.31,
        0.8